devices([
  "iPhone 6",
  "iPhone 6 Plus"
])

# A list of supported languages
languages([
  'en-US',
  'fr-FR'
])

# Where should the resulting screenshots be stored?
output_directory "./screenshots"

# Clears previous screenshots
clear_previous_screenshots

# Latest version of iOS
ios_version '9.1'